openapi: 3.0.0
info:
  title: API LOGGER SERVICE Documentation
  version: '1.0.0'
  description: API документация для сервиса Логирования

tags:
  - name: WSPG
    description: Операции с сервисами WSPG, ADS, VSK

components:
  responses:
    ValidationError:
      description: Ошибка валидации или парсинга
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: 'Ошибка парсинга сервиса. Передан неверный сервис'
              errors:
                type: object
                properties:
                  token:
                    type: array
                    items:
                      type: string
                      example: 'Поле token обязательно для заполнения'
                  service:
                    type: array
                    items:
                      type: string
                      example: 'Поле service обязательно для заполнения'
                  incident:
                    type: array
                    items:
                      type: string
                      example: 'Поле incident обязательно для заполнения'
    UnauthorizedError:
      description: Ошибка авторизации
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: 'Неверный токен'
    ForbiddenError:
      description: Сервис неактивен
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: 'Сервис не активен'

paths:
  /api/v1/add:
    post:
      tags:
        - WSPG, ADS, VSK
      summary: Логирование инцидента
      description: Получает сырые данные инцидента, парсит и сохраняет их
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - incident
                - token
              properties:
                incident:
                  type: object
                  properties:
                    type:
                      type: string
                      example: <WSPG|FROM, ADS|FROM, VSK|FROM>
                    message:
                      type: string
                      example: '123|Message text'
                    object:
                      type: string
                      example: 'Object1'
                    date:
                      type: string
                      format: date-time
                      example: '2024-03-20'
                token:
                  type: string
                  example: 'hash256token'
      responses:
        '200':
          description: Успешное сохранение инцидента
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Инцидент успешно сохранен'
        '400':
          description: Ошибка валидации или парсинга
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Ошибка парсинга сервиса. Передан неверный сервис'
                  errors:
                    type: object
                    properties:
                      token:
                        type: array
                        items:
                          type: string
                          example: 'Поле token обязательно для заполнения'
                      service:
                        type: array
                        items:
                          type: string
                          example: 'Поле service обязательно для заполнения'
                      incident:
                        type: array
                        items:
                          type: string
                          example: 'Поле incident обязательно для заполнения'
        '401':
          description: Неверный токен
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Неверный токен'
